language: node_js
node_js:
  - '8'
deploy:
  provider: heroku
  api_key:
    secure: erJPvQBI8MMXl8XLvg9iySCKrlW3FfgBob0OJt4K1hH2wp4sS/uJmkPunF3ZfbUPlNd4qVRP6EqJ2PH4VRwx2VdoQAl+SK7U1WCrMT0txl6+o5m/r09SyYfN4Rmk8apMb8WEcx2VzEUqm85TApIB4BC10UQZmKyWE8q4fWf+DDH+O3i6CUopfqUv41D/m8jYQ4JGsoKO/ThNmxi8q5X1zAQFjL41glpHz3zUEiMaaMzhK9sM5rdOd1KUUNWkrLR3vC8fK5dOXMbNVJDrk2B2u1VtGgP/gGAFKn15T7/HhKZ0rRiwDVgn9aZLLxN6ul2VRQQKnLxYgu5fr+z50SETjRkVCiFVX6QK6Qja4TYemVR3ouNSg2WhJrPHmBHbrYOxKEXKTb9TALjdLr79mLnT4m37paO+uahPo9N8iqXaNHPIxpecw0OWc2BSiPs28k3eNQ1rpGOjxiDyIQcQ/0NbJoifgedKNkNwZZiyPdNjlBptzvJ/GfXLyDbtO5HZW13g72jz3oACdZm0gQKQ8oxZp5tGjqyIHHQnQryBWusLjYGk2ehSo9JYfY6bjeT49QARufK0GDDp51at65eQF0+HoJnkEEAlSLNfiPYdKGcw9MA/Q1ZVFhHX0AOy9RmejlePie3U9t8Oka5qQyfPOjW/1Q5NqS1bckXK5hQVGRdwSxk=
  app: matheuslbarros-hapi-todo
  skip_cleanup: true
